export enum TypeCteInstanceFile{
    ASIGNACION_CONTRATISTA = 'MAS2',
    DESASIGNACION_CONTRATISTA = 'MDS2',
    ASIGNACION_TECNICO = 'MAST',
    DESASIGNACION_TECNICO = 'MAST',
    IMPORTACION_INSPECCIONES = 'MIN1',
}