export enum TypeInstanceFile{
    GENERACION = 'OTAC',
    REASIGNACION = 'PRSO',
    REASIGNACION_TERRITORIAL = 'PRSO2',
    LEGALIZACION = 'MCIO',
    ASIGNACION_TECNICO = 'MASG',
    DESASIGNACION_TECNICO = 'MDSG'
}