export interface IObra {
    id_territorial?:number,
    id_zona?: number,
    id_obra:number,
    codigo: string,
    codigo_estado:string,
    id_centro_costo: number,
    id_actividad: number,
    id_centro_responsable: number,
    id_proyecto_tipo: number,
    id_obra_tipo: number,
    nombre: string,
    objetivo: string,
    alcance: string,
    presupuesto: number,
    costo_mensual_interventoria: number,
    costo_mensual_aire: number,
    id_plan: number,
    id_pep: number,
    id_orden_trabajo_mano_obra: number,
    id_orden_trabajo_materiales: number,
    ficha_tecnica: string | null,
    fecha_inicio: Date ,
    fecha_fin: Date ,
    id_interventor: number,
    id_estado: number,
    id_departamento: number,
    id_municipio: number,
}